version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: "Asia/Jakarta"
  labels:
    - "dependencies"
  open-pull-requests-limit: 20
