# These are supported funding model platforms

github: ['kennedy-ex', 'riz-ex', 'aryazakaria01', 'FeriEXP', 'AyiinXd']
community_bridge: kennedy-project
custom: ['https://t.me/AyiinSupport', 'https://t.me/AyiinXdSupport']
